name: srcs flakes

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: src
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/eadwu/nixpkgs/archive/develop.tar.gz
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Setup config
        run: |
          mkdir -p ~/.config/nix
          git config user.name actions
          git config user.email "actions@eadwu.flakes"
      - name: Run update script
        run: |
            ./update.sh
            git push origin src
